package main

import (
	"fmt"
	"log"
	"net/http"
	"strings"

	"github.com/jtclarkjr/router-go"
	"github.com/jtclarkjr/router-go/middleware"
	httpSwagger "github.com/swaggo/http-swagger/v2"

	_ "go-openai/docs" // This will be generated by swag
)

// @title           OpenAI REST API
// @version         1.0
// @description     A REST API for OpenAI services including chat completions, image generation, text-to-speech, and speech-to-text.
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8080
// @BasePath  /

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization
func main() {
	r := router.NewRouter()
	r.Use(middleware.Logger)
	r.Use(middleware.RateLimiter)
	r.Use(middleware.Throttle(100))
	r.Use(middleware.EnvVarChecker(
		"OPENAI_API_KEY",
		"BUCKET_NAME",
		"AWS_ENDPOINT_URL_S3",
		"AWS_REGION",
		"AWS_ACCESS_KEY_ID",
		"AWS_SECRET_ACCESS_KEY",
	))

	// Chat routes
	r.Route("/chat", func(r *router.Router) {

		// Text to text chat
		r.Post("/text", completions)

		// Audio to audio chat
		r.Post("/audio", voiceChatFromAudio)

		// Text to chat assistant audio
		r.Post("/text_audio", textVoiceChat)
	})

	// Text to speech
	r.Post("/tts", ttsController)

	// Speech to text
	r.Post("/stt", transcribeToAudio)

	// Text to image
	r.Post("/image", imageGenerate)

	// Swagger UI
	r.Get("/swagger/*", httpSwagger.WrapHandler)

	// serves from server
	r.Get("/files/*", func(w http.ResponseWriter, r *http.Request) {
		fs := http.FileServer(http.Dir("/data"))
		http.StripPrefix("/files/", fs).ServeHTTP(w, r)
	})

	r.Get("/audio/*", func(w http.ResponseWriter, r *http.Request) {
		path := strings.TrimPrefix(r.URL.Path, "/audio/")
		s3URL := fmt.Sprintf("%s/audio/%s", bucketUrl, path)
		http.Redirect(w, r, s3URL, http.StatusFound)
	})

	log.Println("Server starting on port 8080...")
	http.ListenAndServe(":8080", r)
}
